# Generated by Django 3.1.3 on 2021-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.CharField(max_length=30)),
                ('caller_id', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('ringing', models.CharField(max_length=15)),
                ('talking', models.CharField(max_length=15)),
                ('reason', models.CharField(max_length=200)),
                ('totals', models.URLField()),
            ],
        ),
    ]
