from django.db import models

class StaffDetails(models.Model):
    confirmation = models.CharField(max_length=30)
    contract = models.CharField(max_length=30)
    department = models.CharField(max_length=30)
    designation = models.CharField(max_length=30)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
    date_of_employment = models.DateField(auto_now=False, auto_now_add=False)
    date_of_promotion = models.DateField(auto_now=False, auto_now_add=False)
    ecn_mobile_1 = models.CharField(max_length=30)
    education = models.CharField(max_length=30)
    emergency_contact = models.CharField(max_length=30)
    employee_code = models.CharField(max_length=30)
    gender = models.CharField(max_length=30)
    home_address = models.CharField(max_length=30)
    id_passport = models.CharField(max_length=30)
    id_passport_number = models.CharField(max_length=30)
    kra_pin_check = models.CharField(max_length=30)
    kra_pin_no = models.CharField(max_length=30)
    level = models.CharField(max_length=30)
    license_expiry_date = models.CharField(max_length=30)
    license_no = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    mobile_no_2 = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    nationality = models.CharField(max_length=30)
    next_of_kin = models.CharField(max_length=30)
    nhif_no_check = models.CharField(max_length=30)
    nhif_no = models.CharField(max_length=30)
    next_of_kin_mobile_1 = models.CharField(max_length=30)
    next_of_kin_mobile_2 = models.CharField(max_length=30)
    nssf_no_check = models.CharField(max_length=30)
    nssf_no = models.CharField(max_length=30)
    photo_check = models.CharField(max_length=30)
    religion = models.CharField(max_length=30)
    sch_certs = models.CharField(max_length=30)
    staff_info_form = models.CharField(max_length=30)
    staff_mobile_no = models.CharField(max_length=30)
    station = models.CharField(max_length=30)
    tribe = models.CharField(max_length=30)
    contract_type = models.CharField(max_length=30)
    type_of_promotion = models.CharField(max_length=30)
    work_permit = models.CharField(max_length=30)

class Consultants(models.Model):
    gender = models.CharField(max_length=30)
    contract_end = models.CharField(max_length=30)
    contract_in_place = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    date_of_consulting_contract = models.CharField(max_length=30)
    designation = models.CharField(max_length=30)
    id_passport_no = models.CharField(max_length=30)
    work_permit = models.CharField(max_length=30)
    kra_pin = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    mobile_phone_no = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    no_of_times_contract_renewed = models.CharField(max_length=30)
    work_permit_validity = models.CharField(max_length=30)

class EmployeeRelations(models.Model):
    date = models.CharField(max_length=30)
    area = models.CharField(max_length=30)
    category = models.CharField(max_length=30)
    summary = models.CharField(max_length=30)

class FixedTerm(models.Model):
    designation = models.CharField(max_length=30)
    nature_of_contract = models.CharField(max_length=30)
    department = models.CharField(max_length=30)
    date_of_hire = models.CharField(max_length=30)
    contract_lapse_date = models.CharField(max_length=30)
    manager = models.CharField(max_length=30)
    comments = models.CharField(max_length=30)
    name = models.CharField(max_length=30)

class Leave(models.Model):
    name = models.CharField(max_length=30)
    designation = models.CharField(max_length=30)
    branch = models.CharField(max_length=30)
    start_date = models.CharField(max_length=30)
    end_date = models.CharField(max_length=30)
    report_date = models.CharField(max_length=30)
    leave_type = models.CharField(max_length=30)
    days_on_leave = models.CharField(max_length=30)
    comments = models.CharField(max_length=30)

class Training(models.Model):
    date = models.CharField(max_length=30)
    start_time = models.CharField(max_length=30)
    end_time = models.CharField(max_length=30)
    training_topic = models.CharField(max_length=30)
    trainer = models.CharField(max_length=30)
    persons_trained = models.CharField(max_length=30)
    no_of_trainees = models.CharField(max_length=30)
    nita_accredited = models.CharField(max_length=30)